name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint
      id: pylint
      run: |
       # Run Rylint on your code (e.g., on a 'src' directory)
       pylint src > pylink_report.txt || true
    - name: Extract Rating
      id: extract_rating
      run: |
        # Extract the rating from the pylink output
        rating=$(grep "Your code has been rated at" pylint_report.txt | grep -oE '[0-9]+(\.[0-9]+)?')
        echo "Pylint rating: $rating"
        echo "rating=$rating" >> $GITHUB_ENV
    - name: Check Rating and Perform Action Test
      if: ${{ env.rating && env.rating >= 7 }}
      run: |
        echo "Rating is greater than or equal to 7. Passing the action test."
      
    - name: Fail Action Test
      if: ${{ !env.rating || env.rating < 7 }}
      run: |
        echo "Rating is less than 7. Failing the action test."
        exit 1
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
